export enum QrCodeType {
  CALL_PHONE = 'CALL_PHONE',
  SEND_MAIL = 'SEND_MAIL',
  ADD_CONTACT = 'ADD_CONTACT',
  CONNECT_FACEBOOK = 'CONNECT_FACEBOOK',
  CONNECT_LINKEDIN = 'CONNECT_LINKEDIN',
  COLLECT_GOOGLE_REVIEWS = 'COLLECT_GOOGLE_REVIEWS',
  BROWSE_URL = 'BROWSE_URL'
}
